### ISSUE TITLE
plugin uses pre 2023 api ( original : invalid username-password )

### ISSUE THREAD

**Issue by Rostie83** [JackV2020/Domoticz-InternetRadio#2]
After installing Jack's internet radio it doesn't show on the dashboard.
the logfile sais invalid username/password.
unable to create room

As of 2023 Username and password are default on Domoticz. so i tried that, no luck.
created a new user (type user) tried those credentials, no luck.
Which username and password are needed for Internet Radio to create the room?

Domoticz 2024.1

**Comment by JackV2020** [comment]
Whoopsie,
this is a nice one and I promise to look into this but let me explain the cause of the issue. 
As you can see it has been some time since I worked on this plugin and to be honest I am not using it anymore.
In 2023 the application programming interface of Domoticz changed and I updated the plugins which I was using at that moment and since I was not using this anymore I just forgot about it......
Love to do this but it will not be finished this week.
I need to get myself a bluetooth speaker which I also can connect with a cable to my Pi for testing.
So I do not know if you are in the mood of giving it a try yourself or wait for me to do it.
If you want to give it a try yourself you may want to check the documentation on https://www.domoticz.com/wiki/Domoticz_API/JSON_URL%27s
As they say..... to be continued.....
( I am using Domoticz 2024.1 on a Raspberry Pi 4 with bullseye )

**Comment by JackV2020** [comment]
Guess what ? I have this big box in which I keep old cables with strange connectors like scart scsi and whatever and in this box I found this old rechargeable Bluetooth speaker which also has an audio JACK connector speaker and also an audio cable to connect it to my Pi. I tested it with the command 'speaker-test -c1 -twav -l5' and it still works. The -c1 is for 1 speaker. When you have 2 speakers you can use -c2. The -twav is to let a fake voice say what is tested. When yu use -tsine you heer a beep and have to press ctrl-c to stop it. You can also use -tpink to hear some pink noise. The -l5 is to repeat the test 5 times. I also updated the plugin and that works too. Many  stations in the selectors do not work anymore. This is because 'they' changed the internet locations as you find them in internetradio.conf are not valid anymore. I will work out some new lists and after that update this repository.

**Comment by Rostie83** [comment]
Hi Jack,

Great that you found a working bt speaker and are willing to look into this issue.

My JSON is A bit rusty so I'm not much further.
The error  in the log for internet radio are:
ERROR I can not access the image library. Please modify the hardware setup to have the right username and password. 
ERROR could not create selectorswitch "favorieten" 
ERROR could not create selectorswitch "non-stop"
ERROR could not create selectorswitch "Nederland"
ERROR I can not access the image library. Please modify the hardware setup to have the right username and password. 
ERROR I can not access the image library. Please modify the hardware setup to have the right username and password. 
ERROR staring up

Im trying to get internetradio working as my FM reception is playing up very often. As I don't want to ruin my domoticz setup by flashing to Volumio and don't want to use another raspberry I though why not search for something with domoticz. That's what got me here.

For stream links:
https://www.webradiostreams.nl/
https://streamurl.link/

These seem up to date. 

Hopefully you can fix this login issue.

**Comment by JackV2020** [comment]
Hi Rostie83

the issue is solved. This evening I checked and corrected half of the entries in the configuration🥵 and 'my left eye is in my right back pocket' now so I call it an evening now. Btw it works on the jack and the Bluetooth. I am not sure about hdmi because I have no hdmi screen connected yet. 
What country do you live in if I may ask. I live in the south west of the Netherlands and am curious about where my plugins and other stuff is used.

Kind regards 

Jack

⁣BlueMail voor Android downloaden ​

Op 30 jan. 2024 19:52, om 19:52, Rostie83 ***@***.***> schreef:

**Comment by Rostie83** [comment]
Hey Jack,

I'm just another dutchie. Living in Vleuten, near Utrecht.

Op di 30 jan 2024 22:08 schreef Jack Veraart ***@***.***>:

**Comment by JackV2020** [comment]
Hi Rostie83
on jan 31st I sent the update to github.
Did you download that and does it work for you ?

Kind regards,
Jack

**Comment by Rostie83** [comment]
Hi Jack,

Sorry I didnt have time to test until now.
It works flawless. Really happy with your help.

Thanks

Op vr 2 feb 2024 21:47 schreef Jack Veraart ***@***.***>:

**Comment by JackV2020** [comment]
Hi Rosti83,

I am happy to hear that you can listen to the radio. Please note that there is a device with a moving text showing the active station. When you click on that your browser wil go to the station like your pi. The result is that you hear the same station in your browser on your phone/tablet/pc which i think is a nice extra. This way you have have a set which even leaves a Sonos stereo installation far behind😁

Kind regards 

Jack 

Op 6 feb. 2024 20:03, om 20:03, Rostie83 ***@***.***> schreef:
